apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pending-pvc
  namespace: demo
spec:
  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: 100Ti

  storageClassName: nonexistent-storage-class
